Algoritmo "Ex_001"
// Faça um algoritmo que receba dois números inteiros e exiba sua soma.
// Vou fazer amanhã

Var
   // Declare duas variáveis para receber os valores e uma para o resultado

Inicio
  // Faça a atribuição das variáveis (pode ser de forma fixa)
  
  // Efetue o cálculo atribuindo o resultado na última variável
  
  // Escreva na tela o valor da variável com o resultado.

Fimalgoritmo